// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxWakL1qNLIPjpo3L-29LtcPsQs6GDvdc',
    appId: '1:715437358122:web:58098a1cb712ee5bff9753',
    messagingSenderId: '715437358122',
    projectId: 'flutterproject-ff9ee',
    authDomain: 'flutterproject-ff9ee.firebaseapp.com',
    storageBucket: 'flutterproject-ff9ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRaHO2_1knLepRSgTp6DcytQFWT_5FGuA',
    appId: '1:715437358122:android:d4201f18f78e8ed8ff9753',
    messagingSenderId: '715437358122',
    projectId: 'flutterproject-ff9ee',
    storageBucket: 'flutterproject-ff9ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC32-C24BVOzrbXzpLZ6U5NaALonShnOac',
    appId: '1:715437358122:ios:e79df27187fe8757ff9753',
    messagingSenderId: '715437358122',
    projectId: 'flutterproject-ff9ee',
    storageBucket: 'flutterproject-ff9ee.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC32-C24BVOzrbXzpLZ6U5NaALonShnOac',
    appId: '1:715437358122:ios:0ed7b32e955ca933ff9753',
    messagingSenderId: '715437358122',
    projectId: 'flutterproject-ff9ee',
    storageBucket: 'flutterproject-ff9ee.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
